[project]
name = "streamlit-starter"
version = "0.1.0"
description = "Streamlit / Shiny サンプル付きデータアプリ開発テンプレート"
readme = "README.md"
authors = [{name = "Yusuke Hayashi", email = "yusuke8h@gmail.com"}]
requires-python = ">=3.13"
dependencies = [
    "altair>=6.2.2",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "openai>=2.48.0",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "shiny>=1.6.3",
    "streamlit>=1.60.0",
    "streamlit-extras>=1.6.0",
    "tiktoken>=0.13.0",
    "uvicorn>=0.51.0",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pandas-stubs>=3.0.3.260530",
    "pip-audit==2.10.1",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
extend-select = ["ALL"]
# 現在厳しいルールを設定しています。必要に応じてignoreに追加することで緩和してください。
ignore = [
    "D",
    "E501",
    "COM",
    "T201",
    "ERA001",
    "PD901",
    "PLR",
    "PGH003",
    "RUF001",
    "RUF002",
    "RUF003"
]

[tool.mypy]
plugins = [
    "pydantic.mypy",
]
strict = true
warn_unreachable = true
